"""noms francais des types

Revision ID: 1c2531cb24bb
Revises: 6e4cee0a0eee
Create Date: 2026-08-25 21:09:00.217952

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c2531cb24bb"
down_revision: str | Sequence[str] | None = "6e4cee0a0eee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("types", sa.Column("name_fr", sa.String(length=32), nullable=True))
    op.create_index(op.f("ix_types_name_fr"), "types", ["name_fr"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_types_name_fr"), table_name="types")
    op.drop_column("types", "name_fr")
    # ### end Alembic commands ###
