"""noms francais des especes et tables du jcc

Revision ID: 6e4cee0a0eee
Revises: f1a2c3d4e5f6
Create Date: 2026-08-25 20:56:40.254028

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e4cee0a0eee"
down_revision: str | Sequence[str] | None = "f1a2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_sets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("name_fr", sa.String(length=128), nullable=True),
        sa.Column("serie", sa.String(length=128), nullable=True),
        sa.Column("release_date", sa.String(length=16), nullable=True),
        sa.Column("card_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_card_sets_name_en"), "card_sets", ["name_en"], unique=False)
    op.create_index(op.f("ix_card_sets_name_fr"), "card_sets", ["name_fr"], unique=False)
    op.create_index(op.f("ix_card_sets_serie"), "card_sets", ["serie"], unique=False)
    op.create_table(
        "cards",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("set_id", sa.String(length=32), nullable=False),
        sa.Column("local_id", sa.String(length=16), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("name_fr", sa.String(length=128), nullable=True),
        sa.Column("illustrator", sa.String(length=128), nullable=True),
        sa.Column("rarity", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["set_id"], ["card_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_illustrator"), "cards", ["illustrator"], unique=False)
    op.create_index(op.f("ix_cards_local_id"), "cards", ["local_id"], unique=False)
    op.create_index(op.f("ix_cards_name_en"), "cards", ["name_en"], unique=False)
    op.create_index(op.f("ix_cards_name_fr"), "cards", ["name_fr"], unique=False)
    op.create_index(op.f("ix_cards_set_id"), "cards", ["set_id"], unique=False)
    op.add_column("species", sa.Column("name_fr", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_species_name_fr"), "species", ["name_fr"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_species_name_fr"), table_name="species")
    op.drop_column("species", "name_fr")
    op.drop_index(op.f("ix_cards_set_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_name_fr"), table_name="cards")
    op.drop_index(op.f("ix_cards_name_en"), table_name="cards")
    op.drop_index(op.f("ix_cards_local_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_illustrator"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_card_sets_serie"), table_name="card_sets")
    op.drop_index(op.f("ix_card_sets_name_fr"), table_name="card_sets")
    op.drop_index(op.f("ix_card_sets_name_en"), table_name="card_sets")
    op.drop_table("card_sets")
    # ### end Alembic commands ###
