"""schema initial des faits pokemon

Revision ID: 9a59163039b1
Revises:
Create Date: 2026-08-23 23:24:51.882948

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a59163039b1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "species",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=True),
        sa.Column("evolves_from_species_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["evolves_from_species_id"], ["species.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_species_evolves_from_species_id"),
        "species",
        ["evolves_from_species_id"],
        unique=False,
    )
    op.create_index(op.f("ix_species_generation"), "species", ["generation"], unique=False)
    op.create_index(op.f("ix_species_name"), "species", ["name"], unique=True)
    op.create_table(
        "types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_types_name"), "types", ["name"], unique=True)
    op.create_table(
        "versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_versions_name"), "versions", ["name"], unique=True)
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("national_dex_number", sa.Integer(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("height_dm", sa.Integer(), nullable=True),
        sa.Column("weight_hg", sa.Integer(), nullable=True),
        sa.Column("hp", sa.Integer(), nullable=True),
        sa.Column("attack", sa.Integer(), nullable=True),
        sa.Column("defense", sa.Integer(), nullable=True),
        sa.Column("special_attack", sa.Integer(), nullable=True),
        sa.Column("special_defense", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["species_id"], ["species.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pokemon_attack"), "pokemon", ["attack"], unique=False)
    op.create_index(op.f("ix_pokemon_defense"), "pokemon", ["defense"], unique=False)
    op.create_index(op.f("ix_pokemon_hp"), "pokemon", ["hp"], unique=False)
    op.create_index(op.f("ix_pokemon_is_default"), "pokemon", ["is_default"], unique=False)
    op.create_index(op.f("ix_pokemon_name"), "pokemon", ["name"], unique=True)
    op.create_index(
        op.f("ix_pokemon_national_dex_number"), "pokemon", ["national_dex_number"], unique=False
    )
    op.create_index(op.f("ix_pokemon_special_attack"), "pokemon", ["special_attack"], unique=False)
    op.create_index(
        op.f("ix_pokemon_special_defense"), "pokemon", ["special_defense"], unique=False
    )
    op.create_index(op.f("ix_pokemon_species_id"), "pokemon", ["species_id"], unique=False)
    op.create_index(op.f("ix_pokemon_speed"), "pokemon", ["speed"], unique=False)
    op.create_table(
        "pokemon_game_appearances",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["pokemon_id"], ["pokemon.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pokemon_id", "version_id"),
    )
    op.create_table(
        "pokemon_types",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["pokemon_id"], ["pokemon.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["type_id"], ["types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pokemon_id", "type_id"),
        sa.UniqueConstraint("pokemon_id", "slot", name="uq_pokemon_type_slot"),
    )
    op.create_index(op.f("ix_pokemon_types_type_id"), "pokemon_types", ["type_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pokemon_types_type_id"), table_name="pokemon_types")
    op.drop_table("pokemon_types")
    op.drop_table("pokemon_game_appearances")
    op.drop_index(op.f("ix_pokemon_speed"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_species_id"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_special_defense"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_special_attack"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_national_dex_number"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_name"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_is_default"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_hp"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_defense"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_attack"), table_name="pokemon")
    op.drop_table("pokemon")
    op.drop_index(op.f("ix_versions_name"), table_name="versions")
    op.drop_table("versions")
    op.drop_index(op.f("ix_types_name"), table_name="types")
    op.drop_table("types")
    op.drop_index(op.f("ix_species_name"), table_name="species")
    op.drop_index(op.f("ix_species_generation"), table_name="species")
    op.drop_index(op.f("ix_species_evolves_from_species_id"), table_name="species")
    op.drop_table("species")
    # ### end Alembic commands ###
