"""corpus de lore et plongements

Volontairement **sans index vectoriel**. Le corpus tient en ~5 200 entrées de
384 dimensions, soit une douzaine de mégaoctets : un parcours séquentiel les
traverse en quelques millisecondes. Un index ivfflat sur si peu de lignes
dégraderait le rappel — il partitionne un espace qui n'a pas besoin de l'être —
sans gagner de temps mesurable. À reconsidérer si le corpus change d'ordre de
grandeur, et alors seulement après l'avoir mesuré.

`import pgvector.sqlalchemy` est ajouté à la main : l'autogénération d'Alembic
écrit le type sans écrire son import.

Revision ID: c3cba84a8626
Revises: 1c2531cb24bb
Create Date: 2026-08-25 23:22:30.648935

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3cba84a8626"
down_revision: str | Sequence[str] | None = "1c2531cb24bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lore_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.ForeignKeyConstraint(["species_id"], ["species.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("species_id", "text_hash", name="uq_lore_species_text"),
    )
    op.create_index(op.f("ix_lore_chunks_species_id"), "lore_chunks", ["species_id"], unique=False)
    op.create_index(op.f("ix_lore_chunks_text_hash"), "lore_chunks", ["text_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lore_chunks_text_hash"), table_name="lore_chunks")
    op.drop_index(op.f("ix_lore_chunks_species_id"), table_name="lore_chunks")
    op.drop_table("lore_chunks")
    # ### end Alembic commands ###
